language: go

go:
  - 1.16.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test $(go list ./... | grep -v /examples/) -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
